config/routes.rb
Rails.application.routes.draw do
  root 'words#index'

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :favorites, only: [:bookmark]
  
  resources :words do
    get 'favorites/bookmark'
  end
  
  #タグの定義
  get 'tags/:tag', to: 'words#index', as: :tag
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                    
  before_save { email.downcase! }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  
  #アソシエーション
  has_many :words, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_words, through: :favorites, source: :word

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :show]

  # GET /users/1
  # GET /users/1.json
  def show
    @words = Word.where(user_id: @user.id) #userのword一覧を表示
    @favorites = current_user.favorite_words
  end

  # GET /users/new
  def new
    @user = User.new
    flash[:notice] = 'ようこそ、ログインしてください。'
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        FunctionMailer.send_when_create(@user).deliver
        format.html { redirect_to new_session_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    DeletionMailer.send_when_destroy(@user).deliver
    respond_to do |format|
      format.html { redirect_to words_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="field">
      <%= form.label :confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>

  <div class="actions">
    <%= form.submit "送", :class => 'btn btn-info', class:"short_input" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12  text-center">
  
    <center>
    <h1>情報　編纂</h1>

    <%= render 'form', user: @user %>

    </center>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12 ">
  
    <center>
      <h1>新規登録</h1>

      <%= render 'form', user: @user %>

    </center>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
  <div class="col-xs-12 col-md-12 text-center">
    <center>
      
    <!-- ユーザー情報 -->
      <h1>登録情報</h1>
      <p><%= image_tag("/assets/ougi.png") %></p>
      
      <strong>Name:</strong>
      <%= @user.name %>
      <br>
      <% if @user == current_user %>
        <%= link_to '編集', edit_user_path(@user) %>
         |
        <%= link_to '削除', @user, :style=>"color:#ff0000;", method: :delete, data: { confirm: '登録を削除しますか？' } %>
      <% end %>
    </center>
    
  <!-- ユーザーの投稿一覧 -->
    <table class="yoko">
      <h1>一覧</h1>
        
      <% @words.each do |word| %>
      <tr><td>
        <div class="panel">
          <%= link_to word.content, word %>
        </div>
        </td></tr>
        <% end %>
    </table>
    
  <!-- お気に入り一覧 -->
    <table class="yoko">
      <h1>付箋</h1>
      
      <% @favorites.each do |word| %>
        <tr><td>
          <div class="panel">
            <%= link_to word.content, word %>
          </div>
          
          <div class="sub_menu">
          <% tag_cloud word.tag_counts, %w{s m l} do |tag, css_class| %>
            ＃<%= link_to tag.name, tag_path(tag.name), class: css_class %>
          <% end %>
          <%= link_to word.user.name, user_path(word.user_id) %>
          </div>
        </td></tr>
      <% end %>
    </table>
    </div>
  </div>
</div>