config/routes.rb
Rails.application.routes.draw do
  root 'words#index'

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :favorites, only: [:bookmark]
  
  resources :words do
    get 'favorites/bookmark'
  end
  
  #タグの定義
  get 'tags/:tag', to: 'words#index', as: :tag
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/word.rb
class Word < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { in: 1..35 }
  
  #アソシエーション
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :user_id, presence: true
  
  default_scope -> { order(created_at: :desc) }
  
  #検索機能
  def self.search(search)
    if search
      #["#{search}"]がacts-as-taggable-onを使った場合
      Word.tagged_with(["#{search}"], :wild => true) | Word.where(['content LIKE ?', "%#{search}%"])
    else
      Word.limit(7)
    end
  end
  
  #タグ機能
  acts_as_taggable
  
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [ :new, :edit, :show, :destroy, :favorite]

  # GET /words
  # GET /words.json
  def index
    if params[:tag]
      @search_words = Word.tagged_with(params[:tag])
    else
      @search_words = Word.search(params[:search])
    end
  end

  # GET /words/new
  def new
    if params[:back]
      @word = Word.new(word_params)
    else
      @word = Word.new
    end
  end

  # POST /words
  # POST /words.json
  def create
    @word = current_user.words.build(word_params)
    respond_to do |format|
      if @word.save
        format.html { redirect_to words_path }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /words/1
  # GET /words/1.json
  def show
    @favorite = current_user.favorites.find_by(word_id: @word.id)
    @user = @word.user_id
    if params[:tag]
      @word = Word.tagged_with(params[:tag])
    else
     @word = Word.find_by(id: params[:id])
    end
  end
  
  # GET /words/1/edit
  def edit
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:title, :content, :user_id, :name, :tag_list)
    end
end

app/helpers/words_helper.rb
module WordsHelper
  def choose_new_or_edit
    if action_name == 'edit'
      word_path
    end
  end
end

app/views/words/_form.html.erb
<%= form_with(model: word, local: true, url: choose_new_or_edit) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.text_area :content, id: :word_content, :size => "60x3",
    placeholder: "（35文字以内）
　改行できます。" %>
  </div>
  <div class="field">
    <%= form.text_field :tag_list, value: word.tag_list.join(','), placeholder: "タグ1,タグ2" %>
  </div>
  <p>
  <div class="actions">
    <%= form.submit "送", :class => 'btn btn-default', class:"short_input" %>
  </div>
<% end %>

app/views/words/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
    
    <center>
      <h1>編集</h1>

      <%= render 'form', word: @word %>
    </center>

    </div>
  </div>
</div>

app/views/words/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12 text-center">
    
    <!-- 検索フォーム(word.contentのみ） -->
    <p>
    <%= form_tag words_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
      <%= submit_tag "探", :name => nil, class:"short_input" %>
    <% end %>
    </p>
  
    <!-- 新着 -->
    <table class="syotai_row-responsive">
      <% @search_words.each do |word| %>
        <tr><td>  
        <div class="panel">
          <%= link_to word.content, word %>
        </div>
      </td></tr>
      <% end %>
     
    </table>
    </div>
  </div>
</div>

app/views/words/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12 text-center">

    <center>
      <%= render 'form', word: @word %>
    </center>

    </div>
  </div>
</div>

app/views/words/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12 text-center">

    <table class="syotai_row">
      <tr><td>
      
      <!-- ブックマーク機能 -->
        <%= link_to word_favorites_bookmark_path(@word), data: { no_turbolink: true }, id: 'bookmark-link', remote: true do %>
          <%=raw favorite_icon(@word, current_user) %>
        <% end %>

      <!-- word.content -->
        <div class="panel">
          <p><%= simple_format(@word.content) %></p>
        </div>
      </td></tr>
    </table>
    <br>
    
    <!-- タグと投稿者 -->
    <table class="yoko_menu">
      <tr><td  class="yoko_menu">
        <% tag_cloud @word.tag_counts, %w{s m l} do |tag, css_class| %>
          <%= link_to "＃"+tag.name, tag_path(tag.name), class: css_class %>
        <% end %>
        <br>
        <%= simple_time(@word.created_at) %> 
        <%=link_to @word.user.name, user_path(@user) %>
      
      <!-- 投稿者のみの機能 --> 
        <% if @word.user == current_user %>
          (<%= link_to '編集', edit_word_path(@word) %>
          |
          <%= link_to '削除', @word, :style=>"color:#ff0000;", method: :delete, data: { confirm: '削除しますか？' } %>)
        <% end %>
      </td></tr>
    </table>
    </div>
  </div>
</div>