config/routes.rb
Rails.application.routes.draw do
  root 'words#index'

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :favorites, only: [:bookmark]
  
  resources :words do
    get 'favorites/bookmark'
  end
  
  #タグの定義
  get 'tags/:tag', to: 'words#index', as: :tag
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.1.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>言葉あつめ</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    
    <!-- Custom styles for this template -->
    <style>
      body {
        padding-top: 54px;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

    </style>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          
          <!-- ログイン中 -->  
            <% if logged_in? %>
            <li class="nav-item active">
              <%= link_to image_tag("/assets/login.png", :alt => "ログアウト"), session_path(current_user.id), method: :delete %>
            </li>
            <li class="nav-item active">
              <%= link_to "HOME", words_path, class:"nav-link" %>
            </li>
            <!-- モーダルウィンドウ -->
            <li class="nav-item">
              <div id="modal-content">
                <%= link_to '作成', new_word_path, class:"nav-link" %>
                
              </div>
            </li>
            <!-- ここまで -->
            <li class="nav-item">
              <%= link_to '一覧', user_path(current_user.id), class:"nav-link" %>
            </li>
          <!-- ログイン中 -->
            
            <% else %>
          
          <!-- ログアウト -->  
            <li class="nav-item">
              <%= link_to image_tag("/assets/logout.png", :alt => "ログイン"), new_session_path %>
            </li>
            <li class="nav-item active">
              <%= link_to "HOME", words_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_path, class:"nav-link" %>
            </li>
          <!-- ログアウト -->
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    
    <%= yield %>

  
   
  </body>

</html>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>言葉あつめ</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Custom styles for this template -->
    <style>
      body {
        padding-top: 54px;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

    </style>
  
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            
          <!-- HOME -->
            <li class="nav-item active">
              <%= link_to "言葉あつめ", words_path, class:"nav-link" %>
            </li>
          <!-- ログイン中 -->  
            <% if logged_in? %>
            <li class="nav-item">
              <div id="modal-content">
                <%= link_to '作成', new_word_path, class:"nav-link" %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to "#{current_user.name}", user_path(current_user.id), class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to image_tag('/assets/login.png'), session_path(current_user.id), method: :delete,
              :title =>'ログアウト', data: { confirm: 'ログアウトしますか？' } %>
            </li>
            
            <% else %>
          
          <!-- ログアウト -->
            <li class="nav-item">
              <%= link_to "新規登録", new_user_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to image_tag('/assets/logout.png'), new_session_path, :title =>'ログイン' %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
    
    <%= yield %>
    
  </body>
</html>